[package]
name = "gomoku_ai"
version = "0.1.0"
authors = ["Tri Le <trilq1402@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
